# ================================================================
# CARBON BREADTH — BUSCO → GENE / PROTEIN ANNOTATION PREPARATION
# Version: 420
#
# Purpose:
#   Convert the successfully recovered BUSCO candidates into a
#   gene/protein-level candidate table for downstream annotation.
#
# Pipeline:
#
#   BUSCO candidates
#        ↓
#   BUSCO result tables
#        ↓
#   Sequence / protein identifiers
#        ↓
#   Gene / product information where available
#        ↓
#   GO / InterPro / EC / KEGG annotation
#        ↓
#   Pathway grouping
#        ↓
#   Network analysis
#
# Existing ML models and previous outputs are NOT overwritten.
# ================================================================

import os
import re
import json
import time
import warnings
from pathlib import Path

import pandas as pd

warnings.filterwarnings("ignore")

# ================================================================
# CONFIGURATION
# ================================================================

PROJECT = Path(r"C:\Y1000_chassis_project")

RESULTS = (
    PROJECT
    / "results"
    / "stage5_phylogeny_ml_dataset"
    / "phylogeny_aware_ml"
    / "phylogeny_cv"
    / "model_training"
    / "feature_interpretation_420"
)

ANNOTATION_DIR = (
    RESULTS
    / "functional_annotation_420"
)

MAPPING_DIR = (
    ANNOTATION_DIR
    / "busco_gene_mapping_420"
)

OUT_DIR = (
    ANNOTATION_DIR
    / "gene_level_annotation_420"
)

TABLE_DIR = OUT_DIR / "tables"
REPORT_DIR = OUT_DIR / "reports"

TABLE_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------
# INPUT FILES
# ------------------------------------------------

TOP20_FILE = (
    RESULTS
    / "tables"
    / "Carbon_Breadth_top20_BUSCO_features_420.csv"
)

# Actual file generated by the previous successful script
MAPPING_FILE = (
    MAPPING_DIR
    / "tables"
    / "Carbon_Breadth_BUSCO_gene_protein_mapping_420.csv"
)

MAPPING_SUMMARY_FILE = (
    MAPPING_DIR
    / "tables"
    / "Carbon_Breadth_BUSCO_gene_mapping_summary_420.csv"
)

GENE_CANDIDATE_FILE = (
    MAPPING_DIR
    / "tables"
    / "Carbon_Breadth_gene_protein_candidates_420.csv"
)

BUSCO_ANNOTATION_FILE = (
    ANNOTATION_DIR
    / "tables"
    / "Carbon_Breadth_BUSCO_functional_annotation_420.csv"
)

# ------------------------------------------------
# OUTPUT FILES
# ------------------------------------------------

GENE_MASTER_FILE = (
    TABLE_DIR
    / "Carbon_Breadth_gene_level_annotation_candidates_420.csv"
)

BUSCO_GENE_SUMMARY_FILE = (
    TABLE_DIR
    / "Carbon_Breadth_BUSCO_gene_protein_summary_420.csv"
)

UNIQUE_PROTEINS_FILE = (
    TABLE_DIR
    / "Carbon_Breadth_unique_protein_candidates_420.csv"
)

UNIQUE_GENE_IDS_FILE = (
    TABLE_DIR
    / "Carbon_Breadth_unique_gene_candidates_420.csv"
)

ANNOTATION_INPUT_FILE = (
    TABLE_DIR
    / "Carbon_Breadth_annotation_input_420.csv"
)

SUMMARY_JSON = (
    TABLE_DIR
    / "Carbon_Breadth_gene_level_annotation_summary_420.json"
)

REPORT_FILE = (
    REPORT_DIR
    / "Carbon_Breadth_gene_level_annotation_report_420.txt"
)


# ================================================================
# HELPERS
# ================================================================

def clean_string(x):
    """Convert missing values to empty strings."""
    if pd.isna(x):
        return ""
    return str(x).strip()


def find_column(df, candidates):
    """
    Find the first matching column using case-insensitive matching.
    """
    normalized = {
        str(c).strip().lower(): c
        for c in df.columns
    }

    for candidate in candidates:
        key = candidate.strip().lower()
        if key in normalized:
            return normalized[key]

    # partial matching
    for c in df.columns:
        cl = str(c).strip().lower()
        for candidate in candidates:
            if candidate.strip().lower() in cl:
                return c

    return None


def first_nonempty(series):
    """Return first non-empty value."""
    for x in series:
        value = clean_string(x)
        if value:
            return value
    return ""


def unique_join(series, sep="; "):
    """
    Join unique non-empty values.
    """
    values = []

    for x in series:
        value = clean_string(x)

        if value and value not in values:
            values.append(value)

    return sep.join(values)


def safe_read_csv(path, required=True):
    if not path.exists():
        if required:
            raise FileNotFoundError(
                f"\nRequired file not found:\n{path}"
            )
        return pd.DataFrame()

    try:
        return pd.read_csv(path, low_memory=False)
    except Exception as e:
        raise RuntimeError(
            f"\nCould not read:\n{path}\n\nError:\n{e}"
        )


# ================================================================
# HEADER
# ================================================================

print("=" * 80)
print("CARBON BREADTH — BUSCO → GENE / PROTEIN ANNOTATION PREPARATION")
print("=" * 80)

print()
print("Project:")
print(PROJECT)

print()
print("Output directory:")
print(OUT_DIR)

# ================================================================
# LOAD TOP-20 FEATURES
# ================================================================

print()
print("=" * 80)
print("LOADING TOP-20 BUSCO FEATURE IMPORTANCE")
print("=" * 80)

top20 = safe_read_csv(TOP20_FILE)

print("File:")
print(TOP20_FILE)

print()
print("Shape:", top20.shape)

print()
print("Columns:")
print(list(top20.columns))

feature_col = find_column(
    top20,
    ["Feature", "BUSCO_ID", "BUSCO"]
)

if feature_col is None:
    raise KeyError(
        "Could not identify BUSCO feature column in TOP20 file."
    )

top20 = top20.copy()

top20["BUSCO_ID"] = (
    top20[feature_col]
    .astype(str)
    .str.strip()
)

candidate_buscos = (
    top20["BUSCO_ID"]
    .dropna()
    .drop_duplicates()
    .tolist()
)

print()
print("Predictive BUSCO candidates:", len(candidate_buscos))

for busco in candidate_buscos:
    print(busco)


# ================================================================
# LOAD BUSCO → GENE / PROTEIN MAPPING
# ================================================================

print()
print("=" * 80)
print("LOADING BUSCO → GENE / PROTEIN MAPPING")
print("=" * 80)

mapping = safe_read_csv(MAPPING_FILE)

print("File:")
print(MAPPING_FILE)

print()
print("Shape:", mapping.shape)

print()
print("Columns:")
print(list(mapping.columns))


# ================================================================
# IDENTIFY IMPORTANT COLUMNS
# ================================================================

print()
print("=" * 80)
print("IDENTIFYING MAPPING COLUMNS")
print("=" * 80)

mapping_busco_col = find_column(
    mapping,
    ["BUSCO_ID", "BUSCO"]
)

species_col = find_column(
    mapping,
    ["Species", "Organism"]
)

assembly_col = find_column(
    mapping,
    ["Assembly_Accession", "Assembly", "Accession"]
)

sequence_col = find_column(
    mapping,
    [
        "Sequence",
        "Sequence_ID",
        "Contig",
        "Scaffold"
    ]
)

protein_col = find_column(
    mapping,
    [
        "Protein_ID",
        "Protein",
        "ProteinID"
    ]
)

gene_col = find_column(
    mapping,
    [
        "Gene_ID",
        "Gene",
        "GeneID"
    ]
)

product_col = find_column(
    mapping,
    [
        "Product",
        "Protein_Product",
        "Description",
        "Functional_Description"
    ]
)

status_col = find_column(
    mapping,
    ["Status"]
)

start_col = find_column(
    mapping,
    ["Start"]
)

end_col = find_column(
    mapping,
    ["End"]
)

strand_col = find_column(
    mapping,
    ["Strand"]
)

score_col = find_column(
    mapping,
    ["Score"]
)

length_col = find_column(
    mapping,
    ["Length"]
)


print("BUSCO column       :", mapping_busco_col)
print("Species column     :", species_col)
print("Assembly column    :", assembly_col)
print("Sequence column    :", sequence_col)
print("Protein column     :", protein_col)
print("Gene column        :", gene_col)
print("Product column     :", product_col)
print("Status column      :", status_col)
print("Start column       :", start_col)
print("End column         :", end_col)
print("Strand column      :", strand_col)
print("Score column       :", score_col)
print("Length column      :", length_col)


if mapping_busco_col is None:
    raise KeyError(
        "BUSCO_ID is required in the mapping table."
    )


# ================================================================
# NORMALIZE BUSCO IDS
# ================================================================

mapping = mapping.copy()

mapping["BUSCO_ID"] = (
    mapping[mapping_busco_col]
    .astype(str)
    .str.strip()
)

mapping = mapping[
    mapping["BUSCO_ID"].isin(candidate_buscos)
].copy()

print()
print("=" * 80)
print("FILTERING TO PREDICTIVE BUSCO CANDIDATES")
print("=" * 80)

print("Mapping records retained:", len(mapping))

print(
    "Unique BUSCOs:",
    mapping["BUSCO_ID"].nunique()
)


# ================================================================
# LOAD BUSCO FUNCTIONAL ANNOTATION
# ================================================================

print()
print("=" * 80)
print("LOADING EXISTING BUSCO FUNCTIONAL ANNOTATION")
print("=" * 80)

busco_annotation = safe_read_csv(
    BUSCO_ANNOTATION_FILE,
    required=False
)

if busco_annotation.empty:
    print("No BUSCO functional annotation table found.")
else:
    print("File:")
    print(BUSCO_ANNOTATION_FILE)

    print()
    print("Shape:", busco_annotation.shape)

    print()
    print("Columns:")
    print(list(busco_annotation.columns))


# ================================================================
# MERGE PREDICTIVE INFORMATION
# ================================================================

print()
print("=" * 80)
print("ADDING PREDICTIVE MODEL INFORMATION")
print("=" * 80)

importance_columns = [
    "Mean_Importance",
    "SD_Importance",
    "Median_Importance",
    "Min_Importance",
    "Max_Importance",
    "Mean_Baseline_R2",
    "Positive_Importance_Folds",
    "Fold_Stability",
    "Importance_Rank"
]

available_importance = [
    c for c in importance_columns
    if c in top20.columns
]

predictive = top20[
    ["BUSCO_ID"] + available_importance
].drop_duplicates(
    subset=["BUSCO_ID"]
)

mapping = mapping.merge(
    predictive,
    on="BUSCO_ID",
    how="left",
    suffixes=("", "_predictive")
)


# ================================================================
# MERGE FUNCTIONAL DESCRIPTION
# ================================================================

if not busco_annotation.empty:

    annotation_busco_col = find_column(
        busco_annotation,
        ["BUSCO_ID", "BUSCO"]
    )

    if annotation_busco_col:

        busco_annotation = busco_annotation.copy()

        busco_annotation["BUSCO_ID"] = (
            busco_annotation[annotation_busco_col]
            .astype(str)
            .str.strip()
        )

        description_col = find_column(
            busco_annotation,
            [
                "Functional_Description",
                "Description",
                "Product"
            ]
        )

        if description_col:

            descriptions = (
                busco_annotation[
                    ["BUSCO_ID", description_col]
                ]
                .drop_duplicates()
            )

            descriptions = (
                descriptions
                .groupby("BUSCO_ID", as_index=False)
                .agg(
                    BUSCO_Functional_Description=(
                        description_col,
                        first_nonempty
                    )
                )
            )

            mapping = mapping.merge(
                descriptions,
                on="BUSCO_ID",
                how="left"
            )


# ================================================================
# CREATE STANDARDIZED GENE / PROTEIN FIELDS
# ================================================================

print()
print("=" * 80)
print("STANDARDIZING GENE / PROTEIN IDENTIFIERS")
print("=" * 80)


def copy_or_blank(df, source_col):
    if source_col and source_col in df.columns:
        return df[source_col].apply(clean_string)
    return pd.Series(
        [""] * len(df),
        index=df.index
    )


mapping["Sequence_ID"] = copy_or_blank(
    mapping,
    sequence_col
)

mapping["Protein_ID"] = copy_or_blank(
    mapping,
    protein_col
)

mapping["Gene_ID"] = copy_or_blank(
    mapping,
    gene_col
)

mapping["Product_Name"] = copy_or_blank(
    mapping,
    product_col
)

mapping["Species_Name"] = copy_or_blank(
    mapping,
    species_col
)

mapping["Assembly_ID"] = copy_or_blank(
    mapping,
    assembly_col
)


# ================================================================
# IF GENE/PROTEIN IDs ARE NOT EXPLICITLY AVAILABLE
# USE SEQUENCE AS THE PRIMARY RECOVERED LOCUS IDENTIFIER
# ================================================================

mapping["Primary_Locus_ID"] = ""

mapping.loc[
    mapping["Gene_ID"] != "",
    "Primary_Locus_ID"
] = mapping.loc[
    mapping["Gene_ID"] != "",
    "Gene_ID"
]

mapping.loc[
    (mapping["Primary_Locus_ID"] == "")
    & (mapping["Protein_ID"] != ""),
    "Primary_Locus_ID"
] = mapping.loc[
    (mapping["Primary_Locus_ID"] == "")
    & (mapping["Protein_ID"] != ""),
    "Protein_ID"
]

mapping.loc[
    (mapping["Primary_Locus_ID"] == "")
    & (mapping["Sequence_ID"] != ""),
    "Primary_Locus_ID"
] = mapping.loc[
    (mapping["Primary_Locus_ID"] == "")
    & (mapping["Sequence_ID"] != ""),
    "Sequence_ID"
]


# ================================================================
# BUILD GENE-LEVEL CANDIDATE TABLE
# ================================================================

print()
print("=" * 80)
print("BUILDING GENE / PROTEIN CANDIDATE TABLE")
print("=" * 80)

gene_table = mapping.copy()

# Select useful columns first
preferred_columns = [
    "BUSCO_ID",
    "Species_Name",
    "Assembly_ID",
    "Sequence_ID",
    "Gene_ID",
    "Protein_ID",
    "Primary_Locus_ID",
    "Product_Name",
    "BUSCO_Functional_Description",
    "Status",
    "Start",
    "End",
    "Strand",
    "Score",
    "Length"
]

preferred_columns += [
    c for c in importance_columns
    if c in gene_table.columns
]

preferred_columns = [
    c for c in preferred_columns
    if c in gene_table.columns
]

gene_table = gene_table[
    preferred_columns
].copy()


# ================================================================
# SAVE MASTER GENE-LEVEL TABLE
# ================================================================

gene_table.to_csv(
    GENE_MASTER_FILE,
    index=False
)

print()
print("Gene-level master table saved:")
print(GENE_MASTER_FILE)

print()
print("Shape:", gene_table.shape)


# ================================================================
# BUSCO → GENE/PROTEIN SUMMARY
# ================================================================

print()
print("=" * 80)
print("CREATING BUSCO → GENE / PROTEIN SUMMARY")
print("=" * 80)


summary_rows = []

for busco in candidate_buscos:

    sub = gene_table[
        gene_table["BUSCO_ID"] == busco
    ]

    if sub.empty:
        continue

    genes = (
        sub["Gene_ID"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    proteins = (
        sub["Protein_ID"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    sequences = (
        sub["Sequence_ID"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    species = (
        sub["Species_Name"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    products = (
        sub["Product_Name"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    descriptions = (
        sub["BUSCO_Functional_Description"]
        .replace("", pd.NA)
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    row = {
        "BUSCO_ID": busco,

        "Mean_Importance": first_nonempty(
            sub["Mean_Importance"]
        ) if "Mean_Importance" in sub else "",

        "Fold_Stability": first_nonempty(
            sub["Fold_Stability"]
        ) if "Fold_Stability" in sub else "",

        "Species_Count": len(species),

        "Sequence_Count": len(sequences),

        "Gene_ID_Count": len(genes),

        "Protein_ID_Count": len(proteins),

        "Gene_IDs": "; ".join(genes),

        "Protein_IDs": "; ".join(proteins),

        "Sequence_IDs": "; ".join(sequences),

        "Product_Names": "; ".join(products),

        "BUSCO_Functional_Descriptions": "; ".join(
            descriptions
        )
    }

    summary_rows.append(row)


busco_gene_summary = pd.DataFrame(summary_rows)

busco_gene_summary.to_csv(
    BUSCO_GENE_SUMMARY_FILE,
    index=False
)

print()
print("BUSCO summary saved:")
print(BUSCO_GENE_SUMMARY_FILE)


# ================================================================
# UNIQUE PROTEIN CANDIDATES
# ================================================================

print()
print("=" * 80)
print("CREATING UNIQUE PROTEIN CANDIDATE TABLE")
print("=" * 80)

protein_table = gene_table[
    gene_table["Protein_ID"].astype(str).str.strip() != ""
].copy()

protein_table = protein_table.drop_duplicates(
    subset=[
        "BUSCO_ID",
        "Protein_ID",
        "Species_Name"
    ]
)

protein_table.to_csv(
    UNIQUE_PROTEINS_FILE,
    index=False
)

print(
    "Unique protein records:",
    len(protein_table)
)

print(
    "Unique proteins:",
    protein_table["Protein_ID"].nunique()
)


# ================================================================
# UNIQUE GENE IDS
# ================================================================

print()
print("=" * 80)
print("CREATING UNIQUE GENE-ID TABLE")
print("=" * 80)

gene_id_table = gene_table[
    gene_table["Gene_ID"].astype(str).str.strip() != ""
].copy()

gene_id_table = gene_id_table.drop_duplicates(
    subset=[
        "BUSCO_ID",
        "Gene_ID",
        "Species_Name"
    ]
)

gene_id_table.to_csv(
    UNIQUE_GENE_IDS_FILE,
    index=False
)

print(
    "Gene-ID records:",
    len(gene_id_table)
)

print(
    "Unique gene IDs:",
    gene_id_table["Gene_ID"].nunique()
)


# ================================================================
# CREATE DOWNSTREAM ANNOTATION INPUT
# ================================================================

print()
print("=" * 80)
print("CREATING DOWNSTREAM ANNOTATION INPUT")
print("=" * 80)

annotation_input_columns = [
    "BUSCO_ID",
    "Species_Name",
    "Assembly_ID",
    "Sequence_ID",
    "Gene_ID",
    "Protein_ID",
    "Primary_Locus_ID",
    "Product_Name",
    "BUSCO_Functional_Description",
    "Mean_Importance",
    "SD_Importance",
    "Fold_Stability",
    "Importance_Rank"
]

annotation_input_columns = [
    c for c in annotation_input_columns
    if c in gene_table.columns
]

annotation_input = gene_table[
    annotation_input_columns
].drop_duplicates()

annotation_input.to_csv(
    ANNOTATION_INPUT_FILE,
    index=False
)

print()
print("Annotation input saved:")
print(ANNOTATION_INPUT_FILE)

print()
print("Annotation input shape:")
print(annotation_input.shape)


# ================================================================
# SUMMARY STATISTICS
# ================================================================

total_buscos = len(candidate_buscos)

mapped_buscos = (
    mapping["BUSCO_ID"]
    .nunique()
)

unmapped_buscos = (
    total_buscos - mapped_buscos
)

total_mapping_records = len(mapping)

unique_sequences = (
    mapping["Sequence_ID"]
    .replace("", pd.NA)
    .dropna()
    .nunique()
)

unique_proteins = (
    mapping["Protein_ID"]
    .replace("", pd.NA)
    .dropna()
    .nunique()
)

unique_genes = (
    mapping["Gene_ID"]
    .replace("", pd.NA)
    .dropna()
    .nunique()
)

unique_loci = (
    mapping["Primary_Locus_ID"]
    .replace("", pd.NA)
    .dropna()
    .nunique()
)

products_available = (
    mapping["Product_Name"]
    .replace("", pd.NA)
    .dropna()
    .nunique()
)


# ================================================================
# JSON SUMMARY
# ================================================================

summary = {
    "Project": str(PROJECT),

    "Phenotype": "Carbon_Breadth",

    "Candidate_BUSCO_Count": int(total_buscos),

    "Mapped_BUSCO_Count": int(mapped_buscos),

    "Unmapped_BUSCO_Count": int(unmapped_buscos),

    "Mapping_Record_Count": int(total_mapping_records),

    "Unique_Sequence_Count": int(unique_sequences),

    "Unique_Protein_Count": int(unique_proteins),

    "Unique_Gene_ID_Count": int(unique_genes),

    "Unique_Locus_Count": int(unique_loci),

    "Product_Name_Count": int(products_available),

    "Outputs": {
        "Gene_Master": str(GENE_MASTER_FILE),
        "BUSCO_Gene_Summary": str(BUSCO_GENE_SUMMARY_FILE),
        "Unique_Proteins": str(UNIQUE_PROTEINS_FILE),
        "Unique_Gene_IDs": str(UNIQUE_GENE_IDS_FILE),
        "Annotation_Input": str(ANNOTATION_INPUT_FILE)
    },

    "Next_Stage": [
        "Gene/protein annotation",
        "GO annotation",
        "InterPro domain annotation",
        "EC classification",
        "KEGG/pathway mapping",
        "Pathway-level integration",
        "Gene/pathway network construction",
        "Candidate chassis interpretation"
    ]
}

with open(
    SUMMARY_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary,
        f,
        indent=4
    )


# ================================================================
# TEXT REPORT
# ================================================================

with open(
    REPORT_FILE,
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "CARBON BREADTH — BUSCO → GENE / PROTEIN "
        "ANNOTATION PREPARATION REPORT\n"
    )

    f.write("=" * 80 + "\n\n")

    f.write(
        f"Predictive BUSCO candidates: "
        f"{total_buscos}\n"
    )

    f.write(
        f"Mapped BUSCO candidates: "
        f"{mapped_buscos}\n"
    )

    f.write(
        f"Unmapped BUSCO candidates: "
        f"{unmapped_buscos}\n"
    )

    f.write(
        f"Mapping records: "
        f"{total_mapping_records}\n"
    )

    f.write(
        f"Unique sequences: "
        f"{unique_sequences}\n"
    )

    f.write(
        f"Unique proteins: "
        f"{unique_proteins}\n"
    )

    f.write(
        f"Unique gene IDs: "
        f"{unique_genes}\n"
    )

    f.write(
        f"Unique primary loci: "
        f"{unique_loci}\n"
    )

    f.write(
        f"Product names available: "
        f"{products_available}\n\n"
    )

    f.write(
        "INTERPRETATION\n"
    )

    f.write("-" * 80 + "\n")

    f.write(
        "The BUSCO candidates were successfully recovered from "
        "the BUSCO full_table.tsv files. The resulting sequence, "
        "gene and protein identifiers are prepared for downstream "
        "functional annotation.\n\n"
    )

    f.write(
        "Important: BUSCO IDs are orthologous gene-family identifiers "
        "and should not automatically be treated as individual gene "
        "names. Gene/protein-level annotations should therefore be "
        "interpreted in the context of species and assembly.\n\n"
    )

    f.write(
        "NEXT STAGE\n"
    )

    f.write("-" * 80 + "\n")

    f.write(
        "BUSCO → gene/protein → GO/InterPro/EC/KEGG → "
        "pathway grouping → network analysis\n"
    )


# ================================================================
# FINAL CONSOLE OUTPUT
# ================================================================

print()
print("=" * 80)
print("BUSCO → GENE / PROTEIN ANNOTATION PREPARATION COMPLETE")
print("=" * 80)

print()
print("Total BUSCO candidates       :", total_buscos)
print("BUSCO candidates mapped      :", mapped_buscos)
print("BUSCO candidates unmapped    :", unmapped_buscos)
print("Mapping records              :", total_mapping_records)
print("Unique sequence IDs          :", unique_sequences)
print("Unique protein IDs           :", unique_proteins)
print("Unique gene IDs              :", unique_genes)
print("Unique primary loci          :", unique_loci)
print("Product names available      :", products_available)

print()
print("=" * 80)
print("OUTPUTS")
print("=" * 80)

print()
print("Gene-level master table:")
print(GENE_MASTER_FILE)

print()
print("BUSCO → gene/protein summary:")
print(BUSCO_GENE_SUMMARY_FILE)

print()
print("Unique protein candidates:")
print(UNIQUE_PROTEINS_FILE)

print()
print("Unique gene candidates:")
print(UNIQUE_GENE_IDS_FILE)

print()
print("Downstream annotation input:")
print(ANNOTATION_INPUT_FILE)

print()
print("JSON summary:")
print(SUMMARY_JSON)

print()
print("Report:")
print(REPORT_FILE)

print()
print("=" * 80)
print("NEXT SCIENTIFIC STAGE")
print("=" * 80)

print()
print("Gene/protein annotation")
print("        ↓")
print("GO / InterPro / EC / KEGG")
print("        ↓")
print("Pathway grouping")
print("        ↓")
print("Gene/pathway network")
print("        ↓")
print("Candidate chassis interpretation")

print()
print("Existing ML models and OOF predictions were NOT overwritten.")
print("=" * 80)